## Data-Processing:
This project involves reading and processing the subject-dataset. For this purpose, i have intentionally chosen the `Demand-Inventory` based Business-Problem which requires to update and manage the store inventory based on the regulations of the demand-sales chain.

The Project here, deals with ***data-furnishing and extracting useful outputs*** from the subject-data. That requires processing and transforming the raw data.

It would fill all the business-requirements of properly acknowledging the loopholes, drawbacks, and business-faulty standards of the ### Retail_Company, and would allow them to effieciently manage their inventory based on the data-process ideals and certainly optimize their outputs at the industry level.

### Data Building using Python
How can raw retail inventory records be processed and transformed into meaningful store-, product-, and inventory-level metrics that can support demand and inventory decisions?...

Loading the subject-dataset and reading it through pandas library. The python program reads the actual raw data and presents in a tabular format consisting of data-entry rows into their entitled columns!

In [1]:
import pandas as pd
subject_dataset = pd.read_csv("../Datasets_MLmodels/Chosen_Datasets/DemandForecasting/retail_store_inventory.csv")
subject_dataset.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [2]:
subject_dataset.shape

(73100, 15)

In [3]:
subject_dataset.columns.tolist()

['Date',
 'Store ID',
 'Product ID',
 'Category',
 'Region',
 'Inventory Level',
 'Units Sold',
 'Units Ordered',
 'Demand Forecast',
 'Price',
 'Discount',
 'Weather Condition',
 'Holiday/Promotion',
 'Competitor Pricing',
 'Seasonality']

In [4]:
subject_dataset.dtypes

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition      object
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality            object
dtype: object

In [5]:
subject_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [6]:
subject_dataset.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [7]:
len(subject_dataset)

73100

In [8]:
len(subject_dataset.columns)

15

In [9]:
subject_dataset['Date'].dtype

dtype('O')

In [10]:
subject_dataset["Date"] = pd.to_datetime(subject_dataset['Date'])
subject_dataset['Date'].dtype

dtype('<M8[ns]')

In [11]:
subject_dataset['Year'] = subject_dataset['Date'].dt.year
subject_dataset['Month'] = subject_dataset['Date'].dt.month
subject_dataset['Day'] = subject_dataset['Date'].dt.day

In [12]:
subject_dataset.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1

In [13]:
len(subject_dataset.columns)

18

In [14]:
subject_dataset["Inventory Level"].unique()

array([231, 204, 102, 469, 166, 138, 359, 380, 183, 108, 258,  66,  96,
       193, 379, 363, 318, 241, 352, 274, 343, 373, 445, 191, 281, 492,
       460, 304, 113, 157,  67, 389, 465, 197, 242, 398, 234, 221, 115,
       375, 153, 438, 456, 189, 223, 381, 292, 311,  51, 487, 429, 330,
       431, 477, 462, 446, 437, 397, 470, 264, 250,  63, 447, 205, 349,
       406, 228, 263, 203, 143, 211, 111, 415, 384, 436, 180, 185, 478,
       182,  87, 427, 245, 317, 325, 411,  71, 388, 161, 235, 116, 416,
       488, 248, 238, 471, 178,  92,  99, 171, 215, 455,  84, 246, 399,
       156, 402, 132, 218, 131,  93, 344, 340, 296, 472, 308, 434, 287,
       190, 353, 210, 124, 222, 277, 175, 120, 302, 219, 146, 260, 414,
       420, 435, 230, 319,  59, 155, 144, 283, 347, 410,  97, 339, 110,
       348, 458, 403, 198, 254, 100, 442,  76, 257, 119,  60, 289, 418,
        89, 421, 154, 282, 239, 368,  57, 214, 407, 252,  72, 194, 148,
       315, 240, 405, 200, 327, 409, 483,  70, 288, 270, 217, 303, 298,
       365, 271, 134, 290, 448, 186, 413, 112, 268, 495, 324, 297, 169,
       188, 149, 383,  73, 467, 129, 301, 423, 385,  74, 140, 159, 322,
       106, 475,  83, 117, 207, 476,  77, 419, 184, 361, 376, 451,  85,
        91, 209, 127, 367, 404, 494, 150,  94, 430, 168, 109, 493, 425,
       118, 449, 216, 291, 121, 152, 236, 253, 335, 293, 294,  69, 328,
       173, 366, 441, 181, 336, 355, 172, 145, 499, 128, 444,  80, 314,
       167, 103, 364, 439, 101, 466, 237, 220,  86, 334, 482, 278, 338,
       433, 485, 370, 233, 272, 202, 440, 201, 176, 123, 463,  79, 480,
       284, 192, 286, 135, 357, 387, 378, 249, 412, 400, 424, 371,  98,
       299, 392,  68, 358, 269, 243, 262, 481, 377, 350, 104, 372, 224,
       300, 457, 285, 266, 479, 490, 162,  50, 226, 126, 261, 333, 313,
       279, 395, 244, 195, 255, 461, 275, 137, 394, 332, 212,  90, 187,
       177, 391, 158, 164,  61,  81, 453,  88, 323,  53, 227, 342, 125,
       498, 213, 454, 206, 170,  55, 369, 208,  64, 160, 496,  62, 280,
       393, 163, 386, 329, 107, 196, 341, 401, 459, 489, 307, 142, 199,
       247, 351, 306, 450, 443, 491, 139, 267, 486, 310, 356, 259, 225,
       147, 346, 114, 141, 229, 174, 408, 130, 390,  58, 276, 331, 305,
       417, 251, 151, 105, 337, 422, 432,  52, 484, 396,  65, 136,  56,
       473, 345,  78, 256, 362, 165, 500, 133, 374, 426, 382,  54, 320,
       122, 295, 312, 354, 468, 464, 273, 321,  82, 265,  95,  75, 428,
       474, 497, 309, 360, 326, 452, 316, 232, 179])

In [15]:
subject_dataset['Inventory Level'].dtype

dtype('int64')

In [16]:
subject_dataset['Units Sold'].dtype

dtype('int64')

In [17]:
import numpy as np

subject_dataset['Inventory Level'] = pd.to_numeric(subject_dataset['Inventory Level'], errors='coerce')
conditions = [subject_dataset['Inventory Level'] <= 100,
              subject_dataset['Inventory Level'] <= 250 ]
choices = ['Low', 'Medium']
subject_dataset['Inventory Status'] = np.select(conditions, choices, default='Healthy')

In [18]:
subject_dataset['Units Sold'] = pd.to_numeric(subject_dataset['Units Sold'], errors='coerce')

subject_dataset['Inventory Utilization'] = np.where(
    subject_dataset['Inventory Level'] > 0,
    (subject_dataset['Units Sold'] / subject_dataset['Inventory Level']) * 100,
    0.0
)

In [19]:
subject_dataset['Inventory Status'].value_counts()

Inventory Status
Healthy    40280
Medium     24606
Low         8214
Name: count, dtype: int64

In [20]:
subject_dataset[['Inventory Level', 'Units Sold', 'Inventory Utilization']].head()

   Inventory Level  Units Sold  Inventory Utilization
0              231         127              54.978355
1              204         150              73.529412
2              102          65              63.725490
3              469          61              13.006397
4              166          14               8.433735

In [21]:
subject_dataset.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,Inventory Status,Inventory Utilization
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1,Medium,54.978355
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1,Medium,73.529412
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1,Medium,63.725490
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1,Healthy,13.006397
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1,Medium,8.433735

In [22]:
subject_dataset.shape

(73100, 20)

In [23]:
subject_dataset["Order Difference"] = (
    subject_dataset["Units Ordered"] - subject_dataset["Demand Forecast"])
subject_dataset["Sales Difference"] = (
    subject_dataset["Units Sold"] - subject_dataset["Demand Forecast"])

In [24]:
subject_dataset.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,Inventory Status,Inventory Utilization,Order Difference,Sales Difference
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,...,0,29.69,Autumn,2022,1,1,Medium,54.978355,-80.47,-8.47
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,0,66.16,Autumn,2022,1,1,Medium,73.529412,-78.04,5.96
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,...,1,31.32,Summer,2022,1,1,Medium,63.725490,-23.02,-9.02
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,...,1,34.74,Autumn,2022,1,1,Healthy,13.006397,101.82,-1.18
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,...,0,68.95,Summer,2022,1,1,Medium,8.433735,125.74,4.74

In [25]:
for i in range(len(subject_dataset)):
    difference = subject_dataset.loc[i, "Sales Difference"]
    if difference > 0:
        subject_dataset.loc[i, "Demand Status"] = "Higher than Forecast"
    elif difference < 0:
        subject_dataset.loc[i, "Demand Status"] = "Lower than Forecast"
    else:
        subject_dataset.loc[i, "Demand Status"] = "Same as Forecast"

In [26]:
subject_dataset[['Order Difference', 'Sales Difference', 'Demand Status']].head()

   Order Difference  Sales Difference         Demand Status
0            -80.47             -8.47   Lower than Forecast
1            -78.04              5.96  Higher than Forecast
2            -23.02             -9.02   Lower than Forecast
3            101.82             -1.18   Lower than Forecast
4            125.74              4.74  Higher than Forecast

In [27]:
store_summary = subject_dataset.groupby("Store ID").agg(
    Total_Units_Sold=("Units Sold", "sum"),
    Total_Units_Ordered=("Units Ordered", "sum"),
    Average_Inventory=("Inventory Level", "mean"),
    Average_Demand_Forecast=("Demand Forecast", "mean")
).reset_index()

In [28]:
store_summary.head()

,Store ID,Total_Units_Sold,Total_Units_Ordered,Average_Inventory,Average_Demand_Forecast
0,S001,1975750,1613877,273.339945,140.144895
1,S002,1987715,1605169,273.327907,140.973995
2,S003,2022696,1605039,276.872298,143.333906
3,S004,1979245,1608340,272.304788,140.400666
4,S005,2010176,1608902,276.504446,142.620138

In [29]:
product_summary = subject_dataset.groupby("Product ID").agg(
    Total_Units_Sold=("Units Sold", "sum"),
    Total_Units_Ordered=("Units Ordered", "sum"),
    Average_Inventory=("Inventory Level", "mean"),
    Average_Demand_Forecast=("Demand Forecast", "mean")
).reset_index()

In [30]:
product_summary.head()

,Product ID,Total_Units_Sold,Total_Units_Ordered,Average_Inventory,Average_Demand_Forecast
0,P0001,498061,407890,272.993981,141.428605
1,P0002,487827,402077,271.146101,138.496235
2,P0003,493279,402987,274.932695,140.131806
3,P0004,495501,394665,271.556498,140.719283
4,P0005,503648,400964,273.041860,142.762347

In [31]:
low_inventory = subject_dataset[subject_dataset["Inventory Status"] == "Low"]
high_demand_products = product_summary.sort_values(
    by="Total_Units_Sold",
    ascending=False
)

In [32]:
low_inventory.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Competitor Pricing,Seasonality,Year,Month,Day,Inventory Status,Inventory Utilization,Order Difference,Sales Difference,Demand Status
11,2022-01-01,S001,P0012,Clothing,West,66,24,70,26.75,58.25,...,62.21,Spring,2022,1,1,Low,36.363636,43.25,-2.75,Lower than Forecast
12,2022-01-01,S001,P0013,Toys,South,96,42,85,41.46,43.60,...,46.31,Spring,2022,1,1,Low,43.750000,43.54,0.54,Higher than Forecast
30,2022-01-01,S002,P0011,Groceries,West,67,13,33,7.44,34.62,...,33.98,Autumn,2022,1,1,Low,19.402985,25.56,5.56,Higher than Forecast
38,2022-01-01,S002,P0019,Toys,East,67,15,186,34.38,84.99,...,81.02,Winter,2022,1,1,Low,22.388060,151.62,-19.38,Lower than Forecast
52,2022-01-01,S003,P0013,Furniture,North,51,17,172,12.86,73.98,...,76.65,Summer,2022,1,1,Low,33.333333,159.14,4.14,Higher than Forecast

In [33]:
high_demand_products.head()

,Product ID,Total_Units_Sold,Total_Units_Ordered,Average_Inventory,Average_Demand_Forecast
15,P0016,508472,403376,277.505062,143.987133
19,P0020,507708,407810,276.798358,143.662826
13,P0014,507622,402485,277.892202,143.799915
14,P0015,507283,400720,276.408208,143.911885
4,P0005,503648,400964,273.041860,142.762347

In [34]:
subject_dataset.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Competitor Pricing,Seasonality,Year,Month,Day,Inventory Status,Inventory Utilization,Order Difference,Sales Difference,Demand Status
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,...,29.69,Autumn,2022,1,1,Medium,54.978355,-80.47,-8.47,Lower than Forecast
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,66.16,Autumn,2022,1,1,Medium,73.529412,-78.04,5.96,Higher than Forecast
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,...,31.32,Summer,2022,1,1,Medium,63.725490,-23.02,-9.02,Lower than Forecast
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,...,34.74,Autumn,2022,1,1,Healthy,13.006397,101.82,-1.18,Lower than Forecast
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,...,68.95,Summer,2022,1,1,Medium,8.433735,125.74,4.74,Higher than Forecast

In [35]:
subject_dataset.columns[0:22]

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality', 'Year', 'Month', 'Day',
       'Inventory Status', 'Inventory Utilization', 'Order Difference',
       'Sales Difference'],
      dtype='object')

In [36]:
subject_dataset.to_csv("../Datasets_MLmodels/Demand/P02-outputs/processed_inventory_data.csv", index=False, float_format='%.2f')
store_summary.to_csv("outputs/store_summary.csv", index=False)
product_summary.to_csv("outputs/product_summary.csv", index=False)
low_inventory.to_csv("outputs/low_inventory_records.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'outputs'

In [ ]:
subject_dataset['Inventory Status'].value_counts()

In [ ]:
len(subject_dataset)

In [39]:
len(low_inventory)

8214

In [40]:
high_demand_products.head(9)

,Product ID,Total_Units_Sold,Total_Units_Ordered,Average_Inventory,Average_Demand_Forecast
15,P0016,508472,403376,277.505062,143.987133
19,P0020,507708,407810,276.798358,143.662826
13,P0014,507622,402485,277.892202,143.799915
14,P0015,507283,400720,276.408208,143.911885
4,P0005,503648,400964,273.041860,142.762347
8,P0009,502086,398726,275.324761,142.416397
12,P0013,500619,405275,275.111354,142.179360
16,P0017,500510,403335,278.320930,142.012542
10,P0011,499362,400625,272.807661,141.616903